In [6]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4])      #Array yapar
arr

array([1, 2, 3, 4])

In [14]:
math=[[1,2,3],[3,4,5]]
math2=np.array(math)
math2

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
np.arange(0,11)             #range fonk gibi 3. parametre olarak step alıyor

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.zeros((2,3))     #tek dimenson için tuple vermemize gerek yok

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [91]:
np.full((2,3),10) # soldaki ile dolduruyor

array([[10, 10, 10],
       [10, 10, 10]])

In [93]:
x=np.empty((2,2)) # rastgele dizi verir fill ile doldurbiliriz
x.fill(3)

TypeError: fill() takes exactly 1 argument (2 given)

In [34]:
np.linspace(0,20,100)    # 0 dan 20 ye 100 adımda gitmek,adımı parametre olarak vermeyebiliriz,endpoint parametresi false ise 
                                                # son değeri almaz

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [96]:
x=np.eye(6,k=1)         #Identity matris döndürür yanında k parametresi verirsek diagonaldaki 1leri aşağı ya da yukarı kaydırıyor
x                

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [98]:
np.diag([1,4,3,5])   #elemanları köşegene yerleştirmemizi sağladı

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [37]:
np.random.rand(4,4)          #0 ile 1 arasında rastgele sayı üretiyor two dimension için tuple vermeye gerek yok
                             #Uniform dist

array([[0.88337578, 0.10164128, 0.3328243 , 0.55876532],
       [0.47046787, 0.81626483, 0.1510135 , 0.41896785],
       [0.43912634, 0.89277742, 0.51623036, 0.1648787 ],
       [0.02519655, 0.29925263, 0.54078354, 0.68215493]])

In [39]:
np.random.randn(5,5)            #Standart normal dağılım ile 0 cevresinde değer döndürür

array([[ 1.0945884 , -0.06457123,  0.83546765, -0.99839001, -0.25599503],
       [ 0.42532309,  0.87921589,  0.39542135, -0.10003344,  0.7938819 ],
       [-1.5229103 , -2.15235827,  0.45528333, -0.06916238, -0.22373338],
       [ 0.16771095, -1.72102896, -0.36656083, -0.83355988,  1.42764218],
       [ 2.09635345,  0.50871317,  1.09959447, -1.89950261,  0.45531429]])

In [49]:
ran=np.random.randint(1,110,10)   #Random sayı verir, size ı ayarlayabiliriz
ran

array([108, 102,  14,  25,  69,  12,  98,  33,  43,  40])

In [46]:
arr=np.arange(27)
arr
arr.reshape(3,3,3)              #Dimension değiştirebiliyoruz

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [56]:
ran.max()         #max min sum gibi metotlara direkt isim üzerinden ulaşabiliyoruz
ran.argmax()      #arg.. indexi verir

0

In [63]:
ran2=ran.reshape((2,5))

In [69]:
ran2.shape           #shapeyi döndürür
ran2.dtype          # data type ı döndürür

(2, 5)

In [85]:
x=np.array([1,'2',3])   #Upcasting arrayde her şey aynı tür olmalı burada da string olduğu için bütün ifadeyi ona çeviriyor
x.dtype


dtype('<U11')

In [ ]:
#np.array([1,3,4],dtype=np.float) gibi  türü verilebilir
#x.asytpe(dtype.complex) ile tür değiştirilebilir

In [90]:
one=np.ones((5,5))
zero=np.zeros((3,3))
one[1:4,1:4]=zero
one

ValueError: could not broadcast input array from shape (3,3) into shape (3,5)

# Indexing


In [10]:
array=np.arange(23)
array[1:4]
array[0:3]=100
array

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22])

In [11]:
slice_array=array[3:7]
slice_array[:]=99
slice_array


array([99, 99, 99, 99])

In [12]:
slice_array


array([99, 99, 99, 99])

In [80]:
array # Dilimlediğimiz arraydeki değerleri değitirsek bile asıl arraye yansıyor.copy metodu ile yaparsak sıkıntı yok
#np.shares_memory

array([100, 100, 100,  99,  99,  99,  99,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22])

In [32]:
dizi=np.array([[1,2,3],[4,5,6],[56,56,12]])     #kare çıkarmaya çalış


In [35]:
print(dizi[2,1])
print(dizi[2][1])        #Bu şekillerde çağrılabilir

56
56


In [36]:
dizi[:2,1:] #baştan 2.satıra kadar ve 1. sütündan son sütuna kadar olan yerleri döndür

array([[2, 3],
       [5, 6]])

In [41]:
bool_dizi=dizi>50
print(bool_dizi)
print(dizi[bool_dizi])         #İki türlü şeikilde condition belirtebiliriz
print(dizi[dizi>50])

[[False False False]
 [False False False]
 [ True  True False]]
[56 56]
[56 56]


In [ ]:
fatih=np.arange(1,101).reshape(10,10)
fatih

In [43]:
fatih[3:6,1]  # sadece 1 columndaki sayıları getiriyor

SyntaxError: invalid syntax (<ipython-input-43-c7fd630de8c7>, line 1)

##### NumPy Operations & Math Functions


In [44]:
arr=np.arange(50)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [47]:
np.log(arr[arr>0])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ])

In [48]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [57]:
np.add.accumulate(arr,0)

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225], dtype=int32)

In [73]:
np.nansum(arr)    #np.nansum,nanprod Nan olan sayıların çarpımını toplamını veriyor

1225

In [66]:
np.cumsum(arr) #kumuşatif toplamını veriyor (cumprod) çarpımını veriyor

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [77]:
np.not_equal(1,2) #Comparison functions

True

# Kaydetme


In [90]:
# np.save('dosyaismi',array_adı)
# np.load('dosyaismi')

array([32, 42, 52])

# Insert delete stack


In [100]:
x=np.arange(16).reshape(4,4)
y=np.delete(x,1,axis=1) #axis 1 olursa column, 0 olursa row olur. Ayrıca başka bir değ. atarsak eskisinde değişiklik olmaz
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]]


In [112]:
z=np.arange(9).reshape(3,3)
y=np.append(z,[[12,11,13]], axis=0) # 0-> satır, 1->sütun
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12, 11, 13]])

In [113]:
y=np.append(z,[[1],[2],[3]],axis=1)
y

array([[0, 1, 2, 1],
       [3, 4, 5, 2],
       [6, 7, 8, 3]])

In [114]:
x=np.arange(5)
x=np.insert(x,1,3) #2.parametre indis
x

array([0, 3, 1, 2, 3, 4])

In [124]:
x=np.arange(16).reshape(4,4)
print(x)
x=np.insert(x,2,[31,4,32,33],axis=0)
x

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [31,  4, 32, 33],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
x=np.arange(3)
y=np.arange(9).reshape(3,3)                         
z=np.vstack((x,y))               # x i al ynin üstüne koy demek v->vertical,h->horizontal
z

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [144]:
 #fancy indexing slicingden farklıdır
x=np.arange(2)
y=np.arange(9).reshape(3,3)  
print(y)
print(y[x,:1])      # 1 ve 2. satırları getirdi
print(np.shares_memory(x,y))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [3]]
False


# Grup işlemleri



In [149]:
x=[1,2,3,4,5,6,7,6]
y=[6,7,8,9,0,6]

In [154]:
z=np.intersect1d(x,y)   #ortak ifadeleri bastırır
print(z)
print(np.setdiff1d(x,y))   # x in y den farkını bastırır
print(np.union1d(x,y))        # birleştirme
print(np.in1d(x,y))       # x de sırasıyla y deki elemanlar var mı yok mu boolean array dönüyor
print(np.unique(x,y))   # dizideki elemanları distinct olarak dönüyor

[6 7]
[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True]
(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6], dtype=int64))


In [ ]:
#Sort
#np.sort(x) olarak kullanılırsa başka yerde x çağırırsak sıralı olmaz sort(x,axis=0) 2 boyutlu için 
#metot olarak kullanılmalı kalıcı sıralama istiyorsak x.sort()

# İstatistik

In [160]:
x=np.random.randint(1,10,size=(8,))
x

array([5, 4, 5, 7, 4, 8, 7, 2])

In [185]:
print(x.mean())
print(np.median(x))
print(np.std(x))
print(np.average(x))

5.25
5.0
1.8540496217739157
5.25


In [184]:
y=np.random.randint(1,10,size=(4,3))
print(y)
print(np.mean(y[2:3,1:2]))
print(y.mean(axis=0)) #0 sütun 1 satır
print(y.mean(axis=1))

[[6 5 1]
 [7 8 6]
 [3 9 7]
 [7 5 9]]
9.0
[5.75 6.75 5.75]
[4.         7.         6.33333333 7.        ]
